In [9]:
fields = ['code','product_name','brands','categories',
          'ingredients_text','nutriments','labels','countries',
          'nutrition_grade_fr','nova_group']

stringfady = ''
for field in fields:
    if field != fields[-1]:
        stringfady += field + ','
    else: 
        stringfady += field

print(stringfady)

code,product_name,brands,categories,ingredients_text,nutriments,labels,countries,nutrition_grade_fr,nova_group

In [14]:
fields = ['code','product_name','brands','categories',
          'ingredients_text','nutriments','labels','countries',
          'nutrition_grade_fr','nova_group']

field_param = '+'.join(fields)
print(field_param)

code+product_name+brands+categories+ingredients_text+nutriments+labels+countries+nutrition_grade_fr+nova_group

In [5]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [1]:
import pandas as pd
df = pd.read_json('./data/raw_data.json')

In [2]:
df.head()

,brands,categories,code,countries,ingredients_text,labels,nutriments,nutrition_grade_fr,product_name,nova_group
0,maroc.,"Beverages and beverages preparations,Beverages...",6111035000430,Morocco,OBD1 999 999 1112606 266963207 mb,,"{'carbohydrates': 42, 'carbohydrates_100g': 4....",a,Sidi Ali,NaN
1,perly,Snacks,6111242100992,"Morocco,United States",جبن طري بالسكر Fromage frais sucré القيمة الغذ...,,"{'calcium': 0.25, 'calcium_100g': 0.25, 'calci...",unknown,perly,NaN
2,sidi ali,"Beverages and beverages preparations,Beverages...",6111035002175,Morocco,"Sodium, Calcium, Magnésium, Potassium, Bicarbo...",Green Dot,"{'chloride': 0.014, 'chloride_100g': 0.014, 'c...",a,Sidi Ali,1.0
3,"Les Eaux Minérales d'oulmès,Sidi Ali","Beverages and beverages preparations,Beverages...",6111035000058,Morocco,100% mineral water,"ISO 22000,ISO 14001,ISO 45001,ISO 9001",{'fruits-vegetables-legumes-estimate-from-ingr...,a,Eau minérale naturelle,1.0
4,AQUAFINA,"Boissons et préparations de boissons,Boissons,...",6111252421568,المغرب,ouverture et avant le : Voir bouteille. après ...,,"{'alcohol': 0, 'alcohol_100g': 0, 'alcohol_ser...",a,اكوافينا,NaN

In [3]:
import json

with open('./data/raw_data.json', 'r', encoding='utf-8') as f:
    raw_data = json.load(f)

# نفترض raw_data هو list of dicts
df2 = pd.json_normalize(raw_data)

In [4]:
df2.head()

,brands,categories,code,countries,ingredients_text,labels,nutrition_grade_fr,product_name,nutriments.carbohydrates,nutriments.carbohydrates_100g,...,nutriments.en-monounsaturated-fat5_100g,nutriments.en-monounsaturated-fat5_label,nutriments.en-monounsaturated-fat5_unit,nutriments.en-monounsaturated-fat5_value,nutriments.es-vitamin-d2,nutriments.es-vitamin-d2_100g,nutriments.es-vitamin-d2_label,nutriments.es-vitamin-d2_serving,nutriments.es-vitamin-d2_unit,nutriments.es-vitamin-d2_value
0,maroc.,"Beverages and beverages preparations,Beverages...",6111035000430,Morocco,OBD1 999 999 1112606 266963207 mb,,a,Sidi Ali,42.0,4.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,perly,Snacks,6111242100992,"Morocco,United States",جبن طري بالسكر Fromage frais sucré القيمة الغذ...,,unknown,perly,9.4,9.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sidi ali,"Beverages and beverages preparations,Beverages...",6111035002175,Morocco,"Sodium, Calcium, Magnésium, Potassium, Bicarbo...",Green Dot,a,Sidi Ali,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Les Eaux Minérales d'oulmès,Sidi Ali","Beverages and beverages preparations,Beverages...",6111035000058,Morocco,100% mineral water,"ISO 22000,ISO 14001,ISO 45001,ISO 9001",a,Eau minérale naturelle,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AQUAFINA,"Boissons et préparations de boissons,Boissons,...",6111252421568,المغرب,ouverture et avant le : Voir bouteille. après ...,,a,اكوافينا,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def save_to_json(data, path):
    """
    Saves extracted data to a JSON file in a specified path.
    
    Args:
        data (list or dict): The data to be saved as JSON.
        path (str): File path for saving the JSON data.
    
    Returns:
        None
    """
    print("🔃 Data is being saved to JSON file")

    # Ensure directory exists before saving
    directory = ''
    if directory:
        os.makedirs(directory, exist_ok=True)
        
    # Save data to file using UTF-8 encoding
    with open(path, 'w', encoding='utf-8') as json_file:
        json.dump(data, json_file, indent=4, ensure_ascii=False)
    
    print(f"✔️ File successfully saved to {path}")

In [ ]:
save_to_json(sabry, 'raw_data.json')